apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
  labels:
    name: claim-log-1
spec:
  volumeName: pv-log
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
