apiVersion: v1
kind: Pod
metadata:
 name: webapp
 labels:
  name: secret-pod
spec:
 containers:
 - name: secret-container
   image: kodekloud/simple-webapp-mysql
   envFrom:
   - secretRef: 
      name: db-secret
