apiVersion: v1
kind: Pod
metadata:
 name: green-pod
 labels:
  name: configmap-pod
spec:
 containers:
 - name: configmap-container
   image: kodekloud/webapp-color
   envFrom:
   - configMapRef:
      name: green-config
